/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;



/**
 *
 * @author Sasy4
 */
public class Admin_doctor extends javax.swing.JFrame {

    /**
     * Creates new form Admin_doctor
     */
    public Admin_doctor() {
        initComponents();
        jLabel4.setText("Hello Admin  " + Admin.AdminName + " !");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        updateDoctorButton = new javax.swing.JButton();
        viewDoctorListButton = new javax.swing.JButton();
        deleteDoctorButton = new javax.swing.JButton();
        addDoctorButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1300, 650));
        setMinimumSize(new java.awt.Dimension(1300, 650));
        setSize(new java.awt.Dimension(50, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(51, 204, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Admin Services to Manage Doctors");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 560, 74));

        updateDoctorButton.setBackground(new java.awt.Color(153, 204, 255));
        updateDoctorButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        updateDoctorButton.setText("Update Exsisting Doctor Information ►");
        updateDoctorButton.setToolTipText("Enter to Update Exsisting Doctor Information ");
        updateDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDoctorButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updateDoctorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 487, 93));

        viewDoctorListButton.setBackground(new java.awt.Color(153, 204, 255));
        viewDoctorListButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        viewDoctorListButton.setText("View Doctors List  ►");
        viewDoctorListButton.setToolTipText("Enter to arrive View Doctors List   ");
        viewDoctorListButton.setPreferredSize(new java.awt.Dimension(224, 60));
        viewDoctorListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDoctorListButtonActionPerformed(evt);
            }
        });
        jPanel1.add(viewDoctorListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 483, 93));

        deleteDoctorButton.setBackground(new java.awt.Color(153, 204, 255));
        deleteDoctorButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        deleteDoctorButton.setText("Delete Selected Doctor  ►");
        deleteDoctorButton.setToolTipText("Enter to Delete Selected Doctor  ");
        deleteDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDoctorButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteDoctorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 487, 92));

        addDoctorButton.setBackground(new java.awt.Color(153, 204, 255));
        addDoctorButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addDoctorButton.setText("Add New Doctor  ►");
        addDoctorButton.setToolTipText("Enter to Add New Doctor   ");
        addDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctorButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addDoctorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 487, 93));

        ExitButton.setBackground(new java.awt.Color(153, 204, 255));
        ExitButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.setToolTipText("Enter to go the Exit Page   ");
        ExitButton.setFocusable(false);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fatima\\Pictures\\doctorsmang.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fatima\\Pictures\\Logo.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, -1));

        BackButton.setBackground(new java.awt.Color(153, 204, 255));
        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BackButton.setText("Back");
        BackButton.setToolTipText("Back to AdminEntry");
        BackButton.setFocusable(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 100, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Hello Admin [Name]!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 278, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fatima\\Pictures\\1500x800.jpg")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDoctorButtonActionPerformed
        UpdateDoctor updateFrame = new UpdateDoctor();
        updateFrame.setVisible(true);// Show the window
        this.setVisible(false); // Close the current Admin_doctor window 
    }//GEN-LAST:event_updateDoctorButtonActionPerformed

    private void viewDoctorListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDoctorListButtonActionPerformed
       ViewDoctorsList viewdoctorslist = new ViewDoctorsList(); 
        viewdoctorslist.setVisible(true); // Show the window
        this.setVisible(false); // Close the current Admin_doctor window 
    }//GEN-LAST:event_viewDoctorListButtonActionPerformed

    private void deleteDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDoctorButtonActionPerformed
        DeleteDoctor deleteFrame = new DeleteDoctor();
        deleteFrame.setVisible(true);// Show the window
        this.setVisible(false); // Close the current Admin_doctor window 
    }//GEN-LAST:event_deleteDoctorButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        EXITHospital EXIT = new EXITHospital();
        EXIT.setVisible(true); // Show the window
        this.setVisible(false);  // Close the current Admin_doctor window 
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void addDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctorButtonActionPerformed
        AddDoctor addDoc = new AddDoctor();
        addDoc.setVisible(true); // Show the window
        this.setVisible(false); // Close the current Admin_doctor window 
    }//GEN-LAST:event_addDoctorButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
       AdminEntry adminentry = new AdminEntry();
        adminentry.setVisible(true); // Show the window
        this.setVisible(false); // Close the current Admin_doctor window 
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton addDoctorButton;
    private javax.swing.JButton deleteDoctorButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton updateDoctorButton;
    private javax.swing.JButton viewDoctorListButton;
    // End of variables declaration//GEN-END:variables
}
