/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;


/**
 *
 * @author Sasy4
 */
public class Admin_patient extends javax.swing.JFrame {

    /**
     * Creates new form Admin_patient
     */
    public Admin_patient() {
        initComponents();
        jLabel4.setText("Hello Admin  " + Admin.AdminName + " !");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        updatePatientButton = new javax.swing.JButton();
        viewPatientListButton = new javax.swing.JButton();
        deletePatientButton = new javax.swing.JButton();
        addPatientButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ExitButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 650));
        setMinimumSize(new java.awt.Dimension(1300, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(51, 204, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Admin Services to Manage Patients");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 580, 74));

        updatePatientButton.setBackground(new java.awt.Color(153, 204, 255));
        updatePatientButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        updatePatientButton.setText("Update Exsisting Patient Information ►");
        updatePatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePatientButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updatePatientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 487, 93));

        viewPatientListButton.setBackground(new java.awt.Color(153, 204, 255));
        viewPatientListButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        viewPatientListButton.setText("View Patients List  ►");
        viewPatientListButton.setPreferredSize(new java.awt.Dimension(224, 60));
        viewPatientListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatientListButtonActionPerformed(evt);
            }
        });
        jPanel1.add(viewPatientListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 483, 93));

        deletePatientButton.setBackground(new java.awt.Color(153, 204, 255));
        deletePatientButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        deletePatientButton.setText("Delete Selected Patient  ►");
        deletePatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePatientButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deletePatientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 487, 92));

        addPatientButton.setBackground(new java.awt.Color(153, 204, 255));
        addPatientButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addPatientButton.setText("Add New Patient  ►");
        addPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addPatientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 487, 93));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fatima\\Pictures\\doctorsmang.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 420, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fatima\\Pictures\\Logo.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        ExitButton1.setBackground(new java.awt.Color(153, 204, 255));
        ExitButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ExitButton1.setText("Exit");
        ExitButton1.setFocusable(false);
        ExitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(ExitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 100, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Hello Admin [Name]!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 278, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fatima\\Pictures\\1500x800.jpg")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatePatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePatientButtonActionPerformed
         Updatepatients viewPage = new Updatepatients();
        viewPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_updatePatientButtonActionPerformed

    private void viewPatientListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatientListButtonActionPerformed
        ViewPatientsList viewPatients = new ViewPatientsList();
        viewPatients.setVisible(true); // Show the window
        this.setVisible(false); // Close the current Admin_doctor window
    }//GEN-LAST:event_viewPatientListButtonActionPerformed

    private void deletePatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePatientButtonActionPerformed
        DeletePatint viewPage = new DeletePatint();
        viewPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_deletePatientButtonActionPerformed

    private void addPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientButtonActionPerformed
        AddPatient addPatient = new AddPatient();
        addPatient.setVisible(true); // Show the window
        this.setVisible(false);
    }//GEN-LAST:event_addPatientButtonActionPerformed

    private void ExitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButton1ActionPerformed
        EXITHospital EXIT = new EXITHospital();
        EXIT.setVisible(true); // Show the window
        this.setVisible(false);
    }//GEN-LAST:event_ExitButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton1;
    private javax.swing.JButton addPatientButton;
    private javax.swing.JButton deletePatientButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton updatePatientButton;
    private javax.swing.JButton viewPatientListButton;
    // End of variables declaration//GEN-END:variables
}
