/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;



/**
 *
 * @author Sasy4
 */
public class PatientServiceList extends javax.swing.JFrame {

    /**
     * Creates new form PatientServiceList
     */
    public PatientServiceList() {
        
        initComponents();
        jLabel2.setText("Welcome Patient  " + Patient.PatientName + " !");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BookAppointmentButton = new javax.swing.JButton();
        BookTestButton = new javax.swing.JButton();
        ViewMedicalRecordButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        MedicalprescriptionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 650));
        setMinimumSize(new java.awt.Dimension(1300, 650));
        setPreferredSize(new java.awt.Dimension(1300, 650));

        jPanel2.setMaximumSize(new java.awt.Dimension(650, 650));
        jPanel2.setMinimumSize(new java.awt.Dimension(650, 650));
        jPanel2.setPreferredSize(new java.awt.Dimension(650, 650));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Patient");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 170, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fatima\\Pictures\\patient.png")); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("<html>Patients are people who receive medical care or treatment<br> from healthcare professionals. In a system, patients can<br> book appointments and tests, view medical records, and receive <br>prescriptions through the app.<html>");
        jLabel6.setToolTipText("");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 180));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fatima\\Pictures\\Logo.png")); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fatima\\Pictures\\750x8001.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(650, 650));
        jPanel3.setMinimumSize(new java.awt.Dimension(650, 650));
        jPanel3.setPreferredSize(new java.awt.Dimension(650, 650));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Welcome Patient!");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        BookAppointmentButton.setBackground(new java.awt.Color(153, 204, 255));
        BookAppointmentButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BookAppointmentButton.setText("Book Appointment ►");
        BookAppointmentButton.setToolTipText("Enter to arrive Book Appointment ");
        BookAppointmentButton.setMaximumSize(new java.awt.Dimension(244, 36));
        BookAppointmentButton.setMinimumSize(new java.awt.Dimension(244, 36));
        BookAppointmentButton.setPreferredSize(new java.awt.Dimension(244, 36));
        BookAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookAppointmentButtonActionPerformed(evt);
            }
        });
        jPanel3.add(BookAppointmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 390, 90));

        BookTestButton.setBackground(new java.awt.Color(153, 204, 255));
        BookTestButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BookTestButton.setText("Book Test ►");
        BookTestButton.setToolTipText("Enter to arrive Book Test ");
        BookTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookTestButtonActionPerformed(evt);
            }
        });
        jPanel3.add(BookTestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 390, 90));

        ViewMedicalRecordButton.setBackground(new java.awt.Color(153, 204, 255));
        ViewMedicalRecordButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ViewMedicalRecordButton.setText("View Medical Record ►");
        ViewMedicalRecordButton.setToolTipText("Enter to arrive View Medical Record \n");
        ViewMedicalRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMedicalRecordButtonActionPerformed(evt);
            }
        });
        jPanel3.add(ViewMedicalRecordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 390, 90));

        ExitButton.setBackground(new java.awt.Color(153, 204, 255));
        ExitButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.setToolTipText("Enter to go the Exit Page   ");
        ExitButton.setFocusable(false);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jPanel3.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 150, 60));

        MedicalprescriptionButton.setBackground(new java.awt.Color(153, 204, 255));
        MedicalprescriptionButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        MedicalprescriptionButton.setText("Medical prescription ►");
        MedicalprescriptionButton.setToolTipText("Enter to arrive Medical prescription \n  ");
        MedicalprescriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalprescriptionButtonActionPerformed(evt);
            }
        });
        jPanel3.add(MedicalprescriptionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 390, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAppointmentButtonActionPerformed
      
        BookAppointment bookappointment = new BookAppointment(Patient.PatientID);
        bookappointment.setVisible(true); // Show the window
        this.setVisible(false); 
    }//GEN-LAST:event_BookAppointmentButtonActionPerformed

    private void BookTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookTestButtonActionPerformed
        BookTest booktest = new BookTest();
        booktest.setVisible(true); // Show the window
        this.setVisible(false);  
    }//GEN-LAST:event_BookTestButtonActionPerformed

    private void ViewMedicalRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMedicalRecordButtonActionPerformed
        ViewMedicalRecord viewmedicalrecord = new ViewMedicalRecord();
        viewmedicalrecord.setVisible(true); // Show the window
        this.setVisible(false); 
    }//GEN-LAST:event_ViewMedicalRecordButtonActionPerformed

    private void MedicalprescriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalprescriptionButtonActionPerformed
       MedicalPrescription medicalprescription = new MedicalPrescription();
        medicalprescription.setVisible(true); // Show the window
        this.setVisible(false); 
    }//GEN-LAST:event_MedicalprescriptionButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        EXITHospital EXIT = new EXITHospital();
        EXIT.setVisible(true); // Show the window
        this.setVisible(false);  
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientServiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientServiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientServiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientServiceList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientServiceList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookAppointmentButton;
    private javax.swing.JButton BookTestButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton MedicalprescriptionButton;
    private javax.swing.JButton ViewMedicalRecordButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
