/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class UpdateDoctor extends javax.swing.JFrame {
      private Connection conn;

    /**
     * Creates new form NewJFrame
     */
    public UpdateDoctor() {
        initComponents();
        connectToDatabase();
        jLabel7.setText("Hello Doctor " + Doctor.doctorName + " !");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        doctorIDTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        firstNameCheckBox = new javax.swing.JCheckBox();
        firstNameTextField = new javax.swing.JTextField();
        lastNameCheckBox = new javax.swing.JCheckBox();
        lastNameTextField = new javax.swing.JTextField();
        scheduleCheckBox = new javax.swing.JCheckBox();
        scheduleTextField = new javax.swing.JTextField();
        depIDCheckBox = new javax.swing.JCheckBox();
        depIDTextField = new javax.swing.JTextField();
        specializationCheckBox = new javax.swing.JCheckBox();
        specializationComboBox = new javax.swing.JComboBox<>();
        CancelButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 650));
        setMinimumSize(new java.awt.Dimension(1300, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("Hello Admin [Name]!");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 278, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fatima\\Pictures\\updateDoc.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 270, 290));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Update Doctor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 278, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Enter Doctor ID to Update:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 278, -1));

        doctorIDTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        doctorIDTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        jPanel1.add(doctorIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 123, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Choose Fields to Update:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 278, -1));

        firstNameCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        firstNameCheckBox.setForeground(new java.awt.Color(0, 102, 153));
        firstNameCheckBox.setText("Name");
        firstNameCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(firstNameCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 117, -1));

        firstNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        firstNameTextField.setEnabled(false);
        jPanel1.add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 130, 30));

        lastNameCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lastNameCheckBox.setForeground(new java.awt.Color(0, 102, 153));
        lastNameCheckBox.setText("Last Name");
        lastNameCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(lastNameCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 117, -1));

        lastNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        lastNameTextField.setEnabled(false);
        jPanel1.add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 130, 30));

        scheduleCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        scheduleCheckBox.setForeground(new java.awt.Color(0, 102, 153));
        scheduleCheckBox.setText("Schedule");
        scheduleCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(scheduleCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 117, -1));

        scheduleTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        scheduleTextField.setEnabled(false);
        jPanel1.add(scheduleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 130, 30));

        depIDCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        depIDCheckBox.setForeground(new java.awt.Color(0, 102, 153));
        depIDCheckBox.setText("Department ID");
        depIDCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depIDCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(depIDCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, -1, -1));

        depIDTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        depIDTextField.setEnabled(false);
        depIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depIDTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(depIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 130, 30));

        specializationCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        specializationCheckBox.setForeground(new java.awt.Color(0, 102, 153));
        specializationCheckBox.setText("Specialization");
        specializationCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specializationCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(specializationCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, -1, -1));

        specializationComboBox.setBackground(new java.awt.Color(153, 204, 255));
        specializationComboBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        specializationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dentist", "Ophthalmologist", "General Physician", "Cardiologist", "Orthopedic Surgeon", "Dermatologist", "Pediatrician" }));
        specializationComboBox.setEnabled(false);
        specializationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specializationComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(specializationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 237, -1));

        CancelButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(0, 102, 153));
        CancelButton.setText("Cancel");
        CancelButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 190, 61));

        UpdateButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(0, 102, 153));
        UpdateButton.setText("Update Doctor");
        UpdateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255)));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, 190, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fatima\\Pictures\\1500x800.jpg")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameCheckBoxActionPerformed
        firstNameTextField.setEnabled(firstNameCheckBox.isSelected());
    }//GEN-LAST:event_firstNameCheckBoxActionPerformed

    private void lastNameCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameCheckBoxActionPerformed
        lastNameTextField.setEnabled(lastNameCheckBox.isSelected());
    }//GEN-LAST:event_lastNameCheckBoxActionPerformed

    private void scheduleCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleCheckBoxActionPerformed
        scheduleTextField.setEnabled(scheduleCheckBox.isSelected());
    }//GEN-LAST:event_scheduleCheckBoxActionPerformed

    private void depIDCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depIDCheckBoxActionPerformed
        depIDTextField.setEnabled(depIDCheckBox.isSelected());
    }//GEN-LAST:event_depIDCheckBoxActionPerformed

    private void depIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depIDTextFieldActionPerformed

    private void specializationCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specializationCheckBoxActionPerformed
        specializationComboBox.setEnabled(specializationCheckBox.isSelected());
    }//GEN-LAST:event_specializationCheckBoxActionPerformed

    private void specializationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specializationComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specializationComboBoxActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        Admin_doctor adminFrame = new Admin_doctor();
        adminFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        try {
            int doctorID = Integer.parseInt(doctorIDTextField.getText().trim());

            Statement checkStmt = conn.createStatement();
            ResultSet rs = checkStmt.executeQuery("SELECT * FROM Doctor WHERE DoctorID = " + doctorID);

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "Doctor ID not found.");
                return;
            }

            StringBuilder sql = new StringBuilder("UPDATE Doctor SET ");
            boolean update = false;

            if (firstNameCheckBox.isSelected()) {
                sql.append("DR_FIRSTNAME = '").append(firstNameTextField.getText().trim()).append("', ");
                update = true;
            }

            if (lastNameCheckBox.isSelected()) {
                sql.append("DR_LASTTNAME = '").append(lastNameTextField.getText().trim()).append("', ");
                update = true;
            }

            if (depIDCheckBox.isSelected()) {
                sql.append("DepartmentID = ").append(depIDTextField.getText().trim()).append(", ");
                update = true;
            }

            if (specializationCheckBox.isSelected()) {
                sql.append("Specialization = '").append(specializationComboBox.getSelectedItem().toString()).append("', ");
                update = true;
            }

            if (scheduleCheckBox.isSelected()) {
                sql.append("Schedule = '").append(scheduleTextField.getText().trim()).append("', ");
                update = true;
            }

            if (!update) {
                JOptionPane.showMessageDialog(this, "Please select at least one field to update.");
                return;
            }

            sql.setLength(sql.length() - 2); // remove last comma
            sql.append(" WHERE DoctorID = ").append(doctorID);

            Statement updateStmt = conn.createStatement();
            int result = updateStmt.executeUpdate(sql.toString());

            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Doctor updated successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Update failed.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Doctor ID.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void connectToDatabase() {
    try {
     
        conn = DriverManager.getConnection("jdbc:derby://localhost:1527/hospitalDB","hospital", "hospital");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database connection error: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JCheckBox depIDCheckBox;
    private javax.swing.JTextField depIDTextField;
    private javax.swing.JTextField doctorIDTextField;
    private javax.swing.JCheckBox firstNameCheckBox;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox lastNameCheckBox;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JCheckBox scheduleCheckBox;
    private javax.swing.JTextField scheduleTextField;
    private javax.swing.JCheckBox specializationCheckBox;
    private javax.swing.JComboBox<String> specializationComboBox;
    // End of variables declaration//GEN-END:variables
}
